config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_ban', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  get 'kaikki_bisset', to: 'beers#index'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'places', to: 'places#index'
  post 'places', to: 'places#search'
  delete 'signout', to: 'sessions#destroy'
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :styles
  resources :places, only: [:index, :show]
  resource :session, only: [:new, :create, :destroy]
  resource :home, only: [:index]
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  resources :memberships do
    post 'confirm', on: :member
  end

  root 'home#index'

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  has_many :memberships, -> { where confirmed: true}
  has_many :applies, -> { where confirmed: false}, class_name: "Membership"
  has_many :users, through: :memberships

  def to_s
    self.name + ", " + self.city + ", " + self.founded.to_s
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :is_a_member, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_admin, only: [:destroy]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all.order(:name)
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    is_a_member
    @memberships = @beer_club.memberships
    @applies = @beer_club.applies
    @membership = Membership.new
    @membership.beer_club_id = params[:id]
    if current_user && @is_a_member == true
      @beer_club.memberships.each do |m|
        if m.user_id.equal?(current_user.id)
          @membership = m
        end
      end
    end
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        Membership.create({:beer_club_id => @beer_club.id, :user_id => current_user.id, :confirmed => true})
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end

  def is_a_member
    @is_a_member = false
    if current_user
      @beer_club.memberships.each do |m|
        if m.user_id.equal?(current_user.id)
          @is_a_member = true
        end
      end
    end
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.number_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<h2>Listing Beer Clubs</h2>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Founded</th>
    <th>City</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= link_to beer_club.name, beer_club %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <% if current_user && current_user.admin %>
            <td><%= link_to 'Destroy', beer_club, method: :delete, data: {confirm: 'Are you sure?'}, class:'btn-xs btn-danger' %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer club', new_beer_club_path %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @beer_club.name %>
</p>

<p>
  <strong>Founded:</strong>
  <%= @beer_club.founded %>
</p>

<p>
  <strong>City:</strong>
  <%= @beer_club.city %>
</p>

<% if current_user && @is_a_member == false %>
    <%= form_for(@membership) do |f| %>
        <%= f.hidden_field :beer_club_id %>
        <%= f.submit value: "Apply for the club!" %>
    <% end %>
<% end %>
<% if current_user && @is_a_member == true %>
    <%= form_for(@membership, method: "delete") do |f| %>
        <%= f.hidden_field :beer_club_id %>
        <%= f.submit value: "End the membership!" %>
    <% end %>
<% end %>

<h4>Members (<%= @memberships.count %> total):</h4>
<ul>
  <% @memberships.each do |membership| %>
      <li>
        <%= link_to membership.user.username, membership.user %>, joined: <%= membership.created_at.to_date.to_s %>
      </li>
  <% end %>
</ul>
<% if current_user && @is_a_member == true %>
    <h4>Applies</h4>
    <% @applies.each do |apply| %>
        <li>
          <%= link_to apply.user.username, apply.user %>, joined: <%= apply.created_at.to_date.to_s %>
          <%= link_to 'confirm', confirm_membership_path(apply.id), method: :post, class: 'btn-sm btn-danger' %>
        </li>
    <% end %>
    <%= link_to 'Edit', edit_beer_club_path(@beer_club) %> |
<% end %>
<%= link_to 'Back', beer_clubs_path %>