config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_ban', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  get 'kaikki_bisset', to: 'beers#index'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'places', to: 'places#index'
  post 'places', to: 'places#search'
  delete 'signout', to: 'sessions#destroy'
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :styles
  resources :places, only: [:index, :show]
  resource :session, only: [:new, :create, :destroy]
  resource :home, only: [:index]
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  resources :memberships do
    post 'confirm', on: :member
  end

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage

  has_secure_password

  validates :username, uniqueness: true, length: {minimum: 3,
                                                  maximum: 30}
  validates :password, :format => {:with => /\A(?=.*[A-Z])(?=.*[0-9]).{4,}\z/,
                                   message: "must contain at least 1 upper case letter and 1 number!"}

  has_many :ratings, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships
  has_many :beers, through: :ratings

  scope :top3active, -> {
    select("users.id, users.username, count(ratings.id) AS ratings_count").
        joins(:ratings).
        group("users.id").
        order("ratings_count DESC").
        first(5)
  }

  def favorite_beer
    return nil if ratings.empty?
    ratings.sort_by { |r| r.score }.last.beer
  end

  def favorite_style
    favorite :style
  end

  def favorite_brewery
    favorite :brewery
  end

  def favorite(category)
    return nil if ratings.empty?

    rated = ratings.map{ |r| r.beer.send(category) }.uniq
    rated.sort_by { |item| -rating_of(category, item) }.first
  end

  def rating_of(category, item)
    ratings_of = ratings.select{ |r| r.beer.send(category)==item }
    ratings_of.map(&:score).inject(&:+) / ratings_of.count.to_f
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, only: [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:ratings, :beers).all.order(:username)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @memberships = Membership.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user == current_user
      @user.destroy
      respond_to do |format|
        session.clear
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def toggle_ban
    ensure_that_admin
    user = User.find(params[:id])
    user.update_attribute :banned, (not user.banned)

    new_status = user.banned? ? "banned" : "unbanned"

    redirect_to :back, notice:"user #{user.username} #{new_status}"
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <% if @user.new_record? %>
        <div class="field">
          <%= f.label :username %><br />
          <%= f.text_field :username %>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br/>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit class:'btn btn-primary'%>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change Password of <%= current_user.username %></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h2>Users</h2>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Username</th>
    <th>Ratings</th>
    <th>Beers rated</th>
    <th>Average</th>
    <th>Joined</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.ratings.size %></td>
        <td><%= user.beers.size %></td>
        <td><%= round(user.average_rating) %></td>
        <td><%= user.created_at.to_date %></td>
        <% if current_user && current_user.admin %>
            <% if user.banned %>
                <td><span class="label label-info">frozen</span></td>
            <% else %>
                <td></td>
            <% end %>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2>
  <strong><%= @user.username %></strong>
</h2>

<% if @user.banned %>
    <strong><span style="color:red">account frozen</span></strong><br>
<% end %>

<h4> Club memberships:</h4>

<ul>
  <% @user.memberships.each do |membership| %>
      <% if membership.confirmed == true %>
          <li>
            <%= link_to membership.beer_club.name, membership.beer_club %>, joined
            at: <%= membership.created_at.to_date.to_s %>
            <% if @user == current_user %>
                <%= link_to 'delete', membership, method: :delete, data: {confirm: 'Are you sure?'} %>
            <% end %>
          </li>
      <% end %>
  <% end %>
</ul>

<h4> Applies:</h4>

<ul>
  <% @user.memberships.each do |membership| %>
      <% if membership.confirmed == false %>
          <li>
            <%= link_to membership.beer_club.name, membership.beer_club %>, joined
            at: <%= membership.created_at.to_date.to_s %>
            <% if @user == current_user %>
                <%= link_to 'delete', membership, method: :delete, data: {confirm: 'Are you sure?'} %>
            <% end %>
          </li>
      <% end %>
  <% end %>
</ul>

<% if @user.ratings.any? %>
    <p><strong> Favorite beer:</strong> <%= @user.favorite_beer.name %> </p>
    <p><strong> Favorite brewery:</strong> <%= @user.favorite_brewery.name %> </p>
    <p><strong> Favorite style:</strong> <%= @user.favorite_style.name %> </p>

    <p><strong> Average rating:</strong> <%= round(@user.average_rating) %></p>

    <p><strong>Has made <%= pluralize(@user.ratings.count, 'rating') %>:</strong></p>

    <ul>
      <% @user.ratings.each do |r| %>
          <li>
            <%= r %>
            <% if @user == current_user %>
                <%= link_to 'delete', r, method: :delete, data: {confirm: 'Are you sure?'} %>
            <% end %>
          </li>
      <% end %>
    </ul>

<% end %>

<% if current_user && current_user.admin && @user != current_user %>
    <% if @user.banned %>
        <%= link_to 'reactivate account', toggle_ban_user_path(@user.id), method: :post, class: 'btn-sm btn-danger' %>
    <% else %>
        <%= link_to 'freeze account', toggle_ban_user_path(@user.id), method: :post, class: 'btn-sm btn-danger' %>
    <% end %>
<% end %>

<% if @user == current_user || (current_user && current_user.admin) %>
    <%= link_to 'Change password', edit_user_path(@user) %> |
    <%= link_to 'Delete account', user_path, method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>