config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_ban', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  get 'kaikki_bisset', to: 'beers#index'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'places', to: 'places#index'
  post 'places', to: 'places#search'
  delete 'signout', to: 'sessions#destroy'
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :styles
  resources :places, only: [:index, :show]
  resource :session, only: [:new, :create, :destroy]
  resource :home, only: [:index]
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  resources :memberships do
    post 'confirm', on: :member
  end

  root 'home#index'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  include RatingAverage

  validates :name, length: {minimum: 1}

	belongs_to :brewery, touch: true
  belongs_to :style
	has_many :ratings, dependent: :destroy
  has_many :raters, through: :ratings, source: :user

  validates :name, presence: true
  validates :style, presence: true

  def to_s
    self.name + ", " + self.brewery.name
  end

  def self.top(n)
    sorted_by_rating_in_desc_order = Beer.all.sort_by{ |b| -(b.average_rating||0) }
    sorted_by_rating_in_desc_order[0..n]
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]
  before_action :set_breweries_and_styles_for_template, only: [:new, :edit, :create]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :ensure_that_admin, only: [:edit, :update, :destroy]
  before_action :skip_if_cached, only:[:index]

  # GET /beers
  # GET /beers.json
  def index
      @beers = Beer.includes(:brewery, :style).all

      order = params[:order] || 'name'

      @beers = case order
                 when 'name' then
                   @beers.sort_by { |b| b.name }
                 when 'brewery' then
                   @beers.sort_by { |b| b.brewery.name }
                 when 'style' then
                   @beers.sort_by { |b| b.style.name }
               end
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @rating = Rating.new
    @rating.beer = @beer
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  def list
  end

  # POST /beers
  # POST /beers.json
  def create
    ["beerlist-name", "beerlist-brewery", "beerlist-style"].each{ |f| expire_fragment(f) }
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to beers_path, notice: 'Beer was successfully created.' }
        format.json { render :show, status: :created, location: @beer }
      else
        set_breweries_and_styles_for_template
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    ["beerlist-name", "beerlist-brewery", "beerlist-style"].each{ |f| expire_fragment(f) }
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    ["beerlist-name", "beerlist-brewery", "beerlist-style"].each{ |f| expire_fragment(f) }
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_beer
    @beer = Beer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beer_params
    params.require(:beer).permit(:name, :style_id, :brewery_id)
  end

  def set_breweries_and_styles_for_template
    @breweries = Brewery.all
    @styles = Style.all
  end

  def skip_if_cached
    @order = params[:order] || 'name'
    return render :index if request.format.html? and fragment_exist?( "beerlist-#{@order}"  )
  end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :style_id %><br>
    <%= f.select :style_id, options_from_collection_for_select(@styles, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :brewery_id %><br>
    <%= f.select :brewery_id, options_from_collection_for_select(@breweries, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<h2>Beers</h2>

<% cache "beerlist-#{@order}", skip_digest: true do %>
    <table class="table table-hover">
      <thead>
      <tr>
        <th> <%= link_to 'Name', beers_path(order: "name") %> </th>
        <th> <%= link_to 'Style', beers_path(order: "style") %> </th>
        <th> <%= link_to 'Brewery', beers_path(order: "brewery") %> </th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @beers.each do |beer| %>
          <% byebug if beer.brewery.nil? %>
          <tr>
            <td><%= link_to beer.name, beer %></td>
            <td><%= link_to beer.style.name, style_path(beer.style) %></td>
            <td><%= link_to beer.brewery.name, beer.brewery %></td>
            <% if current_user && current_user.admin %>
                <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
                <td><%= link_to 'Destroy', beer, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn-xs btn-danger' %></td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

<br>


<%= link_to('New Beer', new_beer_path) if current_user %><br>
<%= link_to 'List of Breweries', breweries_path %>

app/views/beers/list.html.erb
<h2>Beers</h2>

<table id="beertable" class="table table-hover">
  <tr>
    <th> <a href="#" id="name">Name</a> </th>
    <th> <a href="#" id="style">Style</a> </th>
    <th> <a href="#" id="brewery">Brewery</a> </th>
  </tr>

</table>

app/views/beers/new.html.erb
<h1>New Beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<% cache @beer do %>

    <h2> <%= @beer %> </h2>

    <p>
      <strong>Style:</strong>
      <%= @beer.style.name %>
    </p>

    <% if @beer.ratings.empty? %>
        <p>beer has not yet been rated!</p>
    <% else %>
        <p>Has been rated <%= @beer.ratings.count %> times, average score <%= round(@beer.average_rating) %></p>
    <% end %>
<% end %>

<% if current_user %>
    <h4>give a rating:</h4>

    <%= form_for(@rating) do |f| %>
        <%= f.hidden_field :beer_id %>
        score: <%= f.number_field :score %>
        <%= f.submit %>
    <% end %>

    <% if current_user.admin %>
        <%= edit_and_destroy_buttons(@beer) %>
    <% end %>
<% end %>