config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_ban', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  get 'kaikki_bisset', to: 'beers#index'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'places', to: 'places#index'
  post 'places', to: 'places#search'
  delete 'signout', to: 'sessions#destroy'
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :styles
  resources :places, only: [:index, :show]
  resource :session, only: [:new, :create, :destroy]
  resource :home, only: [:index]
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  resources :memberships do
    post 'confirm', on: :member
  end

  root 'home#index'

end

app/views/layouts/_footer.html.erb
<footer class="navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
    <copyright>
      &copy; Otto Porkka <%= Time.now.year %>
    </copyright>
    <nav>
      <%= image_tag("ruby.ico", class: "footer-icon") %>
      <i>Made with Rails 4.2.7. </i>
      <i>Source code available at github.</i>
      <ul>
        <li><a href="https://www.linkedin.com/in/odporkka/">LinkedIn</a></li>
        <li><a href="https://github.com/odporkka/rubyonrails2017">GitHub</a></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">

    <div class="navbar-header">
      <div class="col">
        <%= link_to image_tag("pint.png", class: "header-icon"), root_path %>
      </div>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links_right' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'breweries', breweries_path %></li>
<li><%= link_to 'beers', beers_path %></li>
<li><%= link_to 'styles', styles_path %></li>
<li><%= link_to 'ratings', ratings_path %></li>
<li><%= link_to 'users', users_path %></li>
<li><%= link_to 'clubs', beer_clubs_path %></li>
<li><%= link_to 'places', places_path %></li>

app/views/layouts/_navigation_links_right.html.erb
<% if not current_user.nil? %>
    <li role="presentation" class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <span class="glyphicon glyphicon-user"></span> <%= current_user.username %> <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to 'My page', current_user %></li>
        <li><%= link_to 'Rate a beer', new_rating_path %></li>
        <li><%= link_to 'Join a club', new_membership_path %></li>
        <li>
          <%= link_to signout_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-in"></span> Log out
          <% end %>
        </li>
      </ul>
    </li>
<% else %>
    <li>
      <%= link_to signin_path do %>
          <span class="glyphicon glyphicon-log-in"></span> Login
      <% end %>
    </li>
    <li>
      <%= link_to signup_path do %>
          <span class="glyphicon glyphicon-user"></span> Sign Up
      <% end %>
    </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Ratebeer" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ratebeer" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= render 'layouts/navigation' %>
</header>

<main role="main" class=".container">
  <div>
    <%= render 'layouts/messages' %>
  </div>
  <div>
    <%= yield %>
  </div>
  <div>
    <%= render 'layouts/footer' %>
  </div>
</main>
</body>
</html>